services:
  pg:
    image: postgres:17.5
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${WALLET__APP__DB__USER}
      POSTGRES_PASSWORD: ${WALLET__APP__DB__PASSWORD}
      POSTGRES_DB: ${WALLET__APP__DB__DATABASE}
    volumes:
        - pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 2s
      retries: 3

  wallet_app:
    build:
      dockerfile: Dockerfile
      context: .

    env_file:
      - .env

    command:
      - "uvicorn"
      - "main:app"
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8000"

    ports:
      - "8000:8000"

    depends_on:
      pg:
        condition: service_healthy

volumes:
  pgdata: